import logging
import re
import csv
from datetime import datetime
from telegram import Update
from telegram.ext import ApplicationBuilder, MessageHandler, filters, ContextTypes

# Enable logging to see errors in the terminal
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO
)


# ---------------------------------------------------------
# THE ANONYMIZER: Strips out personal data using Regex
# ---------------------------------------------------------
def clean_text(text: str) -> str:
    # 1. Remove URLs and Links
    text = re.sub(r"http\S+|www.\S+", "[URL]", text)

    # 2. Remove Email Addresses
    text = re.sub(r"\S+@\S+", "[EMAIL]", text)

    # 3. Remove Phone Numbers (Catches +255... and standard 07... formats)
    text = re.sub(r"\+?\d{9,15}", "[PHONE]", text)

    # 4. Remove Telegram @usernames
    text = re.sub(r"@\w+", "[USER]", text)

    # Strip extra whitespace generated by the removals
    return text.strip()


# ---------------------------------------------------------
# THE LISTENER: Triggers every time a message is sent
# ---------------------------------------------------------
async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    # Ensure the message actually contains text (ignore stickers, photos, etc.)
    if update.message and update.message.text:
        raw_text = update.message.text

        # Pass the text through our Regex cleaner
        cleaned_text = clean_text(raw_text)

        # Get the exact timestamp
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # ---------------------------------------------------------
        # THE SAVER: Appends the clean row to our CSV dataset
        # ---------------------------------------------------------
        # Using 'a' mode (append) so it doesn't overwrite existing data
        with open("swahili_corpus.csv", "a", encoding="utf-8", newline="") as file:
            writer = csv.writer(file)
            writer.writerow([timestamp, cleaned_text])

        # Print a snippet to the console so you know it's working
        print(f"[{timestamp}] Logged: {cleaned_text[:40]}...")


# ---------------------------------------------------------
# MAIN EXECUTION
# ---------------------------------------------------------
if __name__ == "__main__":
    # REPLACE THIS with your actual BotFather token
    BOT_TOKEN = "8657813813:AAGKmrf8nVGCsO84d6KjYukHZuszw-_uwQ8"

    # Build the bot application
    # We are adding connect_timeout and read_timeout to give it 30 seconds to try connecting
    app = (
        ApplicationBuilder()
        .token(BOT_TOKEN)
        .connect_timeout(30.0)
        .read_timeout(30.0)
        .build()
    )

    # Tell the bot to listen to ONLY text messages, and ignore commands (like /start)
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))

    print("🚀 NLP Harvester Bot is booting up and listening...")

    # Keep the script running continuously
    app.run_polling()
